import { Button, Box, Card, CardActions, CardContent, CardHeader, Container, Divider } from '@mui/material';
import SendIcon from '@mui/icons-material/Send';
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [textoDoContrato, setTextoDoContrato] = useState(`
    Lorem Ipsum is simply *********{{nome}}********* text of the printing and 
    typesetting industry. Lorem Ipsum has been the ** *******{{uf}}********* standard dummy text ever since the 1500s,
    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has *********{{idade}}*********
    not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the *********{{cpf}}********* with 
    the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`);

  const [cliente, setCliente] = useState({
    nome: 'Gian Silva',
    uf: 'RS',
    cpf: '8618371623',
    idade: 27
  });

  const substuirDadosDoContrato = () => {
    setTextoDoContrato((textoAtualDoContrato) => {

      Object.keys(cliente).map((cadaNomeDaProprierade) => {
        textoAtualDoContrato = textoAtualDoContrato.replace(
          `{{${cadaNomeDaProprierade}}}`, cliente[cadaNomeDaProprierade]
        );
      });
      
      return textoAtualDoContrato;
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Macacateus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          py: 2
        }}
      >
        <Container maxWidth={false}>
          <Card>
            <CardHeader title="Contrato"/>
            <Divider/>
            <CardContent>
                <p>{textoDoContrato}</p>  
            </CardContent>
            <Divider/>
            <CardActions 
              sx={{
                display: 'flex',  
                flexDirection: 'row',
                justifyContent: 'right',
                alignItems: 'right'
              }}
            >
              <Button
                endIcon={<SendIcon/>}
                color='reguaPrimary'
                variant="contained"
                onClick={() => substuirDadosDoContrato()}
              >
                Criar contrato 
              </Button>
            </CardActions> 
          </Card>
        </Container>
      </Box>

    </div>
)}
