import Head from 'next/head'
import { useState } from 'react'
import { DashboardLayout } from '../components/dashboard-layout';
import SButton from '../infra/strtucture/buttons/SButton';
import styles from '../styles/Home.module.css'

const HomeDoGi = () => {

  const [textoDoContrato, setTextoDoContrato] = useState(`Bunda {{nome} {{uf}} {{cpf}} {{idade}}`);

  const [cliente, setCliente] = useState({
    nome: 'Gian Silva',
    uf: 'RS',
    cpf: '8618371623',
    idade: 27
  });

  const substuirDadosDoContrato = () => {
    setTextoDoContrato((textoAtualDoContrato) => {

      Object.keys(cliente).map((cadaNomeDaProprierade) => {
        textoAtualDoContrato = textoAtualDoContrato.replace(
          `{{${cadaNomeDaProprierade}}}`, cliente[cadaNomeDaProprierade]
        );
      });
      
      return textoAtualDoContrato;
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Macacateus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {textoDoContrato}  
      </div>
      <br/>
      <SButton
        callback={substuirDadosDoContrato}
        tipoDoBotao={'primario'}
      >
        PRIMA
      </SButton>
      <SButton
        callback={substuirDadosDoContrato}
        tipoDoBotao={'secundario'}
      >
        SECUNDA
      </SButton>
    </div>
  )
}

HomeDoGi.getLayout = (page) => (
  <DashboardLayout>
    {page}
  </DashboardLayout>
);

export default HomeDoGi;