import { AttachFile } from '@mui/icons-material';
import { Button, Card, Box, CardHeader, CardContent, Divider, Container} from '@mui/material';
import Head from 'next/head'
import { useState } from 'react'
import { DashboardLayout } from '../components/dashboard-layout';

const HomeDoGi = () => {

  const [textoDoContrato, setTextoDoContrato] = useState("Faça o upload do arquivo.");

  const [cliente, setCliente] = useState();

  const substuirDadosDoContrato = () => {
    setTextoDoContrato((textoAtualDoContrato) => {

      Object.keys(cliente).map((cadaNomeDaProprierade) => {
        textoAtualDoContrato = textoAtualDoContrato.replace(
          `{{${cadaNomeDaProprierade}}}`, cliente[cadaNomeDaProprierade]
        );
      });
      
      return textoAtualDoContrato;
    });
  }

  const handleUpload = async (e) => {
    e.preventDefault();
    const reader = new FileReader();
    reader.onload = async (e) => { 
      const text = (e.target.result);
      setTextoDoContrato(text);
    };
    reader.readAsText(e.target.files[0]);
  }

  const handleInputCreation = (text) => {
    //Ler o arquivo e identificar a primeira chave dupla;
    //Utilizar o termo entre as chaves duplas e a chave de fechamento como nome das variáveis do objeto;

    const obj = {};
    Object.assign(obj, "lkjhasdjlasdk");
  }

  return (<>
    <Head>
      <title>Core</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box sx={{
          m: 2
        }}
    >
      <Card>
        <CardHeader 
          title={'Core'}
        />
        <Divider/>
        <CardContent sx={{
            display: 'flex',
            flexDirection: 'row',
            justifyContent: 'space-between',
          }}
        >
          <Box  sx={{
            display: 'flex',
            flexDirection: 'column',
            width: '50%',
            borderRight: '1px solid gray',
            p: 2
          }}>
            <div>
              {textoDoContrato}  
            </div>
          </Box>
        
          <Box  sx={{
            width: '50%',
            p: 2,
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            gap: 1
          }}>

            <Button
              fullWidth
              variant='outlined'
              component="label"
              tipoDoBotao={'primario'}
              endIcon={<AttachFile/>}
            >
              Upload File
              <input
                type="file"
                hidden
                onChange={event => handleUpload(event)}
              />
            </Button>
            <Button
              fullWidth
              variant='contained'
              onClick={() => substuirDadosDoContrato()}
            >
              Substituir dados
            </Button>
          </Box>
        </CardContent>
      </Card>
    </Box>
  </>)
}

HomeDoGi.getLayout = (page) => (
  <DashboardLayout>
    {page}
  </DashboardLayout>
);

export default HomeDoGi;