import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [textoDoContrato, setTextoDoContrato] = useState(`
    Lorem Ipsum is simply *********{{nome}}********* text of the printing and 
    typesetting industry. Lorem Ipsum has been the *********{{uf}}********* standard dummy text ever since the 1500s,
    when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has *********{{idade}}*********
    not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the *********{{cpf}}********* with 
    the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`);

  const [cliente, setCliente] = useState({
    nome: 'Filippi de Paula',
    uf: 'SP',
    cpf: '72518156054',
    idade: 26
  });

  const substituirDados = () => {
    setTextoDoContrato((textoAtual) => {
      Object.keys(cliente).map((element) => textoAtual = textoAtual.replace(`{{${element}}}`, cliente[element]));
      return textoAtual;
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Macacateus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {textoDoContrato}  
      </div>
      <br/>
      <button
        onClick={() => substituirDados()}
      >
        Criar contrato
      </button>
    </div>
  )
}
